Chores/backport k8s
OpenSourcePolitics/decidim-ditp pull request #26
Opened 2023-07-21 14:44 UTC by armandfardeau

#### :tophat: Description
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?
- [Notion card]()

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access Backoffice
* Go to organization settings
* See ...

#### Tasks
- [ ] Add specs
- [ ] Add note about overrides in OVERLOADS.md
- [ ] In case of new dependencies or version bump, update related documentation

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2023-07-21 15:09 UTC, Quentinchampenois requested changes

2023-07-21 15:09 UTC, Quentinchampenois commented on Gemfile.lock
> +GIT
Rebuild Gemfile.lock

2023-07-21 15:09 UTC, Quentinchampenois commented on config/initializers/decidim.rb
> +    config.available_locales = ENV.fetch("AVAILABLE_LOCALES", "fr").split(",").map(&:to_sym)
```suggestion
    config.available_locales = ENV.fetch("AVAILABLE_LOCALES", "en,fr").split(",").map(&:to_sym)
```

2023-07-21 15:09 UTC, Quentinchampenois commented on config/initializers/decidim.rb
Add Decidim::Initiatives block

2023-07-21 15:09 UTC, Quentinchampenois commented on config/initializers/decidim.rb
> +  config.enable_machine_translations = Rails.application.secrets.translator[:enabled]
Remove machine translations

2023-07-21 15:09 UTC, Quentinchampenois commented on config/initializers/decidim.rb
> +Decidim.module_eval do
Remove reminder registry

2023-07-21 15:09 UTC, Quentinchampenois commented on config/locales/fr.yml
> +  rack_attack:
Re add translations and keep rack_attack

2023-07-21 15:09 UTC, Quentinchampenois commented on config/secrets.yml
>      fallback: <%= ENV["HELP_SCOUT_BEACON_ID_FALLBACK"] %>
Add hotjar

2023-07-21 15:09 UTC, Quentinchampenois commented on config/secrets.yml
> +    france_connect:
Remove france_connect

2023-07-21 15:09 UTC, Quentinchampenois commented on config/secrets.yml
> +  translator:
Remove translator

2023-07-21 15:09 UTC, Quentinchampenois commented on spec/system/confirmation_spec.rb
> +require "spec_helper"
Still needed ?

2023-07-27 09:16 UTC, paulinebessoles approved these changes

2023-08-10 09:54 UTC, merged